function y = get_dihedral(vertex_o, vertex_s, face_o)

y = [];
for i = 1:size(face_o)
    y = [y; acosd(dot([vertex_o(face_o(i,1),1)-vertex_o(face_o(i,2),1),vertex_o(face_o(i,1),2)-... 
        vertex_o(face_o(i,2),2), vertex_o(face_o(i,1),3)-vertex_o(face_o(i,2),3)], ...
        [vertex_s(face_o(i,1),1)-vertex_s(face_o(i,2),1),vertex_s(face_o(i,1),2)-...
        vertex_s(face_o(i,2),2),vertex_s(face_o(i,1),3)-vertex_s(face_o(i,2),3)])/...
        (norm([vertex_o(face_o(i,1),1)-vertex_o(face_o(i,2),1),vertex_o(face_o(i,1),2)-... 
        vertex_o(face_o(i,2),2), vertex_o(face_o(i,1),3)-vertex_o(face_o(i,2),3)])* ...
        norm([vertex_s(face_o(i,1),1)-vertex_s(face_o(i,2),1),vertex_s(face_o(i,1),2)-...
        vertex_s(face_o(i,2),2),vertex_s(face_o(i,1),3)-vertex_s(face_o(i,2),3)])))];
    y = [y; acosd(dot([vertex_o(face_o(i,1),1)-vertex_o(face_o(i,3),1),vertex_o(face_o(i,1),2)-... 
        vertex_o(face_o(i,3),2), vertex_o(face_o(i,1),3)-vertex_o(face_o(i,3),3)], ...
        [vertex_s(face_o(i,1),1)-vertex_s(face_o(i,3),1),vertex_s(face_o(i,1),2)-...
        vertex_s(face_o(i,3),2),vertex_s(face_o(i,1),3)-vertex_s(face_o(i,3),3)])/...
        (norm([vertex_o(face_o(i,1),1)-vertex_o(face_o(i,3),1),vertex_o(face_o(i,1),2)-... 
        vertex_o(face_o(i,3),2), vertex_o(face_o(i,1),3)-vertex_o(face_o(i,3),3)])* ...
        norm([vertex_s(face_o(i,1),1)-vertex_s(face_o(i,3),1),vertex_s(face_o(i,1),2)-...
        vertex_s(face_o(i,3),2),vertex_s(face_o(i,1),3)-vertex_s(face_o(i,3),3)])))];
    y = [y; acosd(dot([vertex_o(face_o(i,2),1)-vertex_o(face_o(i,3),1),vertex_o(face_o(i,2),2)-... 
        vertex_o(face_o(i,3),2), vertex_o(face_o(i,2),3)-vertex_o(face_o(i,3),3)], ...
        [vertex_s(face_o(i,2),1)-vertex_s(face_o(i,3),1),vertex_s(face_o(i,2),2)-...
        vertex_s(face_o(i,3),2),vertex_s(face_o(i,2),3)-vertex_s(face_o(i,3),3)])/...
        (norm([vertex_o(face_o(i,2),1)-vertex_o(face_o(i,3),1),vertex_o(face_o(i,2),2)-... 
        vertex_o(face_o(i,3),2), vertex_o(face_o(i,2),3)-vertex_o(face_o(i,3),3)])* ...
        norm([vertex_s(face_o(i,2),1)-vertex_s(face_o(i,3),1),vertex_s(face_o(i,2),2)-...
        vertex_s(face_o(i,3),2),vertex_s(face_o(i,2),3)-vertex_s(face_o(i,3),3)])))];
end
y = real(y);

end